[package]
name = "fast_rsync"
version = "0.1.0"
authors = ["Dropbox Engineering", "bacher09, Artyom Pavlov (RustCrypto/hashes/MD4)"]
license = "Apache-2.0"
description = "An optimized implementation of librsync in pure Rust."
repository = "https://github.com/dropbox/fast_rsync"
keywords = ["rsync"]
edition = "2018"

[dependencies]
arrayref = "0.3.6"
packed_simd = "0.3.3"

[dev-dependencies]
librsync = "0.2.0"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
rand = "0.7.3"
